import type { CountryCode } from './countries.js';
import type { ProspectResult } from './prospectTypes.js';

const DEMO_BY_COUNTRY: Record<CountryCode, ProspectResult[]> = {
  GB: [
    {
      id: 'demo-gb-1',
      country: 'GB',
      firstName: 'Sarah',
      lastName: 'Mitchell',
      fullName: 'Sarah Mitchell',
      title: 'Chief Executive Officer',
      officerRole: 'director',
      company: 'BrightPath Digital Ltd',
      companyNumber: '12345678',
      industry: 'Computer programming & IT',
      sicCodes: ['62012'],
      region: 'London',
      address: '42 Tech Lane, Shoreditch, London',
      postcode: 'EC2A 4NE',
      email: 'hello@brightpathdigital.co.uk',
      phone: '+44 20 7946 0958',
      website: 'https://www.brightpathdigital.co.uk',
      enriched: true,
      appointedOn: '2019-03-15',
    },
    {
      id: 'demo-gb-2',
      country: 'GB',
      firstName: 'James',
      lastName: 'Hartley',
      fullName: 'James Hartley',
      title: 'Managing Director',
      officerRole: 'director',
      company: 'Hartley Construction Group Ltd',
      companyNumber: '23456789',
      industry: 'Construction of buildings',
      sicCodes: ['41100'],
      region: 'West Midlands',
      address: '18 Industrial Park Road, Birmingham',
      postcode: 'B1 2AA',
      phone: '+44 121 496 0123',
      enriched: false,
    },
    {
      id: 'demo-gb-3',
      country: 'GB',
      firstName: 'Priya',
      lastName: 'Sharma',
      fullName: 'Priya Sharma',
      title: 'Chief Financial Officer',
      officerRole: 'director',
      company: 'NorthStar Finance Partners Ltd',
      companyNumber: '34567890',
      industry: 'Financial services',
      sicCodes: ['64191'],
      region: 'North West',
      address: '7 King Street, Manchester',
      postcode: 'M2 4WU',
      email: 'info@northstarfinance.co.uk',
      enriched: false,
    },
  ],
  US: [
    {
      id: 'demo-us-1',
      country: 'US',
      firstName: 'Michael',
      lastName: 'Reed',
      fullName: 'Michael Reed',
      title: 'Chief Executive Officer',
      officerRole: 'executive',
      company: 'Summit Cloud Systems Inc',
      companyNumber: '1847293',
      industry: 'Software & IT services',
      sicCodes: ['7374'],
      region: 'CA',
      address: '500 Market Street, San Francisco, CA',
      postcode: '94105',
      email: 'press@summitcloud.io',
      phone: '+1 415 555 0142',
      enriched: true,
    },
    {
      id: 'demo-us-2',
      country: 'US',
      firstName: 'Jennifer',
      lastName: 'Walsh',
      fullName: 'Jennifer Walsh',
      title: 'Chief Financial Officer',
      officerRole: 'executive',
      company: 'Atlas Health Analytics Corp',
      companyNumber: '2093847',
      industry: 'Healthcare services',
      sicCodes: ['8093'],
      region: 'MA',
      address: '200 Boylston Street, Boston, MA',
      postcode: '02116',
      phone: '+1 617 555 0198',
      enriched: false,
    },
    {
      id: 'demo-us-3',
      country: 'US',
      firstName: 'David',
      lastName: 'Nguyen',
      fullName: 'David Nguyen',
      title: 'Director of Operations',
      officerRole: 'director',
      company: 'Lone Star Logistics LLC',
      companyNumber: '8839201',
      industry: 'Logistics & transport',
      sicCodes: ['4210'],
      region: 'TX',
      address: '1200 Commerce St, Dallas, TX',
      postcode: '75201',
      enriched: false,
    },
  ],
  AU: [
    {
      id: 'demo-au-1',
      country: 'AU',
      firstName: 'Olivia',
      lastName: 'Chen',
      fullName: 'Olivia Chen',
      title: 'Managing Director',
      officerRole: 'director',
      company: 'Pacific Solar Solutions Pty Ltd',
      companyNumber: '51824793601',
      industry: 'Renewable energy',
      sicCodes: ['tech'],
      region: 'NSW',
      address: '88 George Street, Sydney',
      postcode: '2000',
      email: 'info@pacificsolar.com.au',
      phone: '+61 2 9012 3456',
      enriched: true,
    },
    {
      id: 'demo-au-2',
      country: 'AU',
      firstName: 'Liam',
      lastName: 'O\'Brien',
      fullName: 'Liam O\'Brien',
      title: 'Chief Executive Officer',
      officerRole: 'director',
      company: 'Harbour FinTech Group Pty Ltd',
      companyNumber: '67123459832',
      industry: 'Financial services',
      sicCodes: ['finance'],
      region: 'VIC',
      address: '101 Collins Street, Melbourne',
      postcode: '3000',
      enriched: false,
    },
  ],
  CA: [
    {
      id: 'demo-ca-1',
      country: 'CA',
      firstName: 'Sophie',
      lastName: 'Tremblay',
      fullName: 'Sophie Tremblay',
      title: 'Chief Executive Officer',
      officerRole: 'director',
      company: 'Maple Analytics Inc',
      companyNumber: 'BC1234567',
      industry: 'Technology & software',
      sicCodes: ['tech'],
      region: 'BC',
      address: '1055 West Georgia St, Vancouver',
      postcode: 'V6E 3P3',
      email: 'hello@mapleanalytics.ca',
      enriched: false,
    },
    {
      id: 'demo-ca-2',
      country: 'CA',
      firstName: 'Robert',
      lastName: 'Singh',
      fullName: 'Robert Singh',
      title: 'Director',
      officerRole: 'director',
      company: 'Great Lakes Manufacturing Ltd',
      companyNumber: 'ON9876543',
      industry: 'Manufacturing',
      sicCodes: ['manufacturing'],
      region: 'ON',
      address: '250 Bay Street, Toronto',
      postcode: 'M5J 2N8',
      phone: '+1 416 555 0177',
      enriched: false,
    },
  ],
  DE: [
    {
      id: 'demo-de-1',
      country: 'DE',
      firstName: 'Klaus',
      lastName: 'Weber',
      fullName: 'Klaus Weber',
      title: 'Geschäftsführer (CEO)',
      officerRole: 'director',
      company: 'RheinTech GmbH',
      companyNumber: 'HRB 123456',
      industry: 'Technology & software',
      sicCodes: ['tech'],
      region: 'NRW',
      address: 'Königsallee 12, Düsseldorf',
      postcode: '40212',
      email: 'kontakt@rheintech.de',
      phone: '+49 211 555 0190',
      enriched: true,
    },
    {
      id: 'demo-de-2',
      country: 'DE',
      firstName: 'Anna',
      lastName: 'Schmidt',
      fullName: 'Anna Schmidt',
      title: 'Finanzvorstand (CFO)',
      officerRole: 'director',
      company: 'Bavaria MedDevice AG',
      companyNumber: 'HRB 789012',
      industry: 'Healthcare',
      sicCodes: ['health'],
      region: 'Bayern',
      address: 'Maximilianstraße 8, Munich',
      postcode: '80539',
      enriched: false,
    },
  ],
  FR: [
    {
      id: 'demo-fr-1',
      country: 'FR',
      firstName: 'Camille',
      lastName: 'Dubois',
      fullName: 'Camille Dubois',
      title: 'Directrice Générale (CEO)',
      officerRole: 'director',
      company: 'Lumière Digital SAS',
      companyNumber: '892 456 123',
      industry: 'Media & marketing',
      sicCodes: ['media'],
      region: 'Île-de-France',
      address: '15 Rue de Rivoli, Paris',
      postcode: '75001',
      email: 'contact@lumiere-digital.fr',
      enriched: false,
    },
    {
      id: 'demo-fr-2',
      country: 'FR',
      firstName: 'Pierre',
      lastName: 'Martin',
      fullName: 'Pierre Martin',
      title: 'Directeur Financier (CFO)',
      officerRole: 'director',
      company: 'Alpine Logistics SARL',
      companyNumber: '814 223 991',
      industry: 'Logistics & transport',
      sicCodes: ['logistics'],
      region: 'Auvergne-Rhône-Alpes',
      address: '22 Cours Lafayette, Lyon',
      postcode: '69003',
      phone: '+33 4 78 555 012',
      enriched: false,
    },
  ],
  IN: [
    {
      id: 'demo-in-1',
      country: 'IN',
      firstName: 'Arjun',
      lastName: 'Patel',
      fullName: 'Arjun Patel',
      title: 'Chief Executive Officer',
      officerRole: 'director',
      company: 'NexGen Software Pvt Ltd',
      companyNumber: 'U72900MH2018PTC123456',
      industry: 'Technology & software',
      sicCodes: ['tech'],
      region: 'Maharashtra',
      address: 'Bandra Kurla Complex, Mumbai',
      postcode: '400051',
      email: 'info@nexgensoftware.in',
      phone: '+91 22 5555 0100',
      enriched: true,
    },
    {
      id: 'demo-in-2',
      country: 'IN',
      firstName: 'Ananya',
      lastName: 'Reddy',
      fullName: 'Ananya Reddy',
      title: 'Chief Financial Officer',
      officerRole: 'director',
      company: 'Deccan Health Systems Pvt Ltd',
      companyNumber: 'U85110KA2015PTC987654',
      industry: 'Healthcare',
      sicCodes: ['health'],
      region: 'Karnataka',
      address: 'Outer Ring Road, Bengaluru',
      postcode: '560103',
      enriched: false,
    },
  ],
  AE: [
    {
      id: 'demo-ae-1',
      country: 'AE',
      firstName: 'Fatima',
      lastName: 'Al Mansoori',
      fullName: 'Fatima Al Mansoori',
      title: 'Chief Executive Officer',
      officerRole: 'director',
      company: 'Desert Horizon Properties LLC',
      companyNumber: 'DED-884921',
      industry: 'Real estate',
      sicCodes: ['finance'],
      region: 'Dubai',
      address: 'Sheikh Zayed Road, Dubai',
      postcode: '',
      email: 'info@deserthorizon.ae',
      phone: '+971 4 555 0188',
      enriched: true,
    },
    {
      id: 'demo-ae-2',
      country: 'AE',
      firstName: 'Omar',
      lastName: 'Hassan',
      fullName: 'Omar Hassan',
      title: 'Managing Director',
      officerRole: 'director',
      company: 'Gulf Trade Partners FZE',
      companyNumber: 'FZ-772104',
      industry: 'Consulting & professional services',
      sicCodes: ['consulting'],
      region: 'Abu Dhabi',
      address: 'Al Maryah Island, Abu Dhabi',
      postcode: '',
      enriched: false,
    },
  ],
  SG: [
    {
      id: 'demo-sg-1',
      country: 'SG',
      firstName: 'Wei Ming',
      lastName: 'Tan',
      fullName: 'Wei Ming Tan',
      title: 'Chief Executive Officer',
      officerRole: 'director',
      company: 'Orchid FinTech Pte Ltd',
      companyNumber: '201912345A',
      industry: 'Financial services',
      sicCodes: ['finance'],
      region: 'Singapore',
      address: '1 Raffles Place, Singapore',
      postcode: '048616',
      email: 'hello@orchidfintech.sg',
      enriched: false,
    },
  ],
  IE: [
    {
      id: 'demo-ie-1',
      country: 'IE',
      firstName: 'Connor',
      lastName: 'Murphy',
      fullName: 'Connor Murphy',
      title: 'Managing Director',
      officerRole: 'director',
      company: 'Emerald SaaS Ltd',
      companyNumber: 'IE654321',
      industry: 'Technology & software',
      sicCodes: ['tech'],
      region: 'Dublin',
      address: 'Grand Canal Dock, Dublin',
      postcode: 'D02',
      email: 'team@emeraldsaas.ie',
      phone: '+353 1 555 0144',
      enriched: true,
    },
  ],
  NL: [
    {
      id: 'demo-nl-1',
      country: 'NL',
      firstName: 'Eva',
      lastName: 'de Vries',
      fullName: 'Eva de Vries',
      title: 'Chief Executive Officer',
      officerRole: 'director',
      company: 'Windmill Data BV',
      companyNumber: 'KVK 81234567',
      industry: 'Technology & software',
      sicCodes: ['tech'],
      region: 'North Holland',
      address: 'Herengracht 100, Amsterdam',
      postcode: '1015 BS',
      email: 'info@windmilldata.nl',
      enriched: false,
    },
  ],
  ZA: [
    {
      id: 'demo-za-1',
      country: 'ZA',
      firstName: 'Thabo',
      lastName: 'Nkosi',
      fullName: 'Thabo Nkosi',
      title: 'Chief Executive Officer',
      officerRole: 'director',
      company: 'Cape Digital Solutions (Pty) Ltd',
      companyNumber: '2019/123456/07',
      industry: 'Technology & software',
      sicCodes: ['tech'],
      region: 'Western Cape',
      address: 'Waterfront, Cape Town',
      postcode: '8001',
      phone: '+27 21 555 0166',
      enriched: false,
    },
    {
      id: 'demo-za-2',
      country: 'ZA',
      firstName: 'Nomsa',
      lastName: 'Dlamini',
      fullName: 'Nomsa Dlamini',
      title: 'Director',
      officerRole: 'director',
      company: 'Joburg Logistics Group (Pty) Ltd',
      companyNumber: '2015/987654/07',
      industry: 'Logistics & transport',
      sicCodes: ['logistics'],
      region: 'Gauteng',
      address: 'Sandton, Johannesburg',
      postcode: '2196',
      email: 'ops@joburglogistics.co.za',
      enriched: false,
    },
  ],
};

export function getDemoProspectsForCountry(country: CountryCode): ProspectResult[] {
  return DEMO_BY_COUNTRY[country] ?? DEMO_BY_COUNTRY.GB;
}

/** @deprecated Use getDemoProspectsForCountry */
export const DEMO_PROSPECTS = DEMO_BY_COUNTRY.GB;